import { Request, Response, Router } from 'express';
import UserRoutes from './User';
import ProductRoutes from './Product';
import FormRoute from './Form.route';
import questionRoute from './question.route';
import inscriptionRoute from './inscription.route';
import PoolRoute from './Pool.route';
import FileRoute from './files.route';
import SettingRoutes from './Setting';
import detailInscriptionRoute from './Detail.inscription.route';
import SettingAdmin from './settins.route';
import HelperRoute from '../routes/helpers.route';
import PaypalRoutes from './paypal.route';
import mailChip from './Mailchip';
const router = Router();
router.use(HelperRoute);
router.use(detailInscriptionRoute);
router.use(UserRoutes);
router.use(SettingAdmin);
router.use(FileRoute);
router.use(ProductRoutes);
router.use(SettingRoutes);
router.use(FormRoute);
router.use(PoolRoute);
router.use(inscriptionRoute);
router.use(questionRoute);
router.use(PaypalRoutes);
router.use(mailChip);
router.get('/', (req, res) => {
  // res.render("index", { message: "hello world" });
  res.render('index');
});
export default router;
